PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX dbnary: <http://kaiko.getalp.org/dbnary#>
PREFIX dbnary-eng: <http://kaiko.getalp.org/dbnary/eng/>

SELECT ?p ?mwe
FROM <http://kaiko.getalp.org/dbnary/eng>
WHERE {
    ?p dbnary:derivedFrom ?mwe.
    ?mwe a ontolex:MultiWordExpression.
}

